version: "3"
services:
  ubuntu:
    image: ubuntu:18.04
    ports:
    - 
    environment:
      - volumes:
    command: tail -f /dev/null
    tty: true
    
  web:
    # replace username/repo:tag 
    #build: .
    image: nginx
    ports:
    - "80:8080"
  db:
    image: mysql
    ports: 
    - "3306:3306"  
    environment:
      MSQL_ROOT_PASSWORD: "password"
      MSQL_USER: "user"
      MSQL_PASSWORD: "password"
      MSQL_DATABASE: "db"
    # To persist data on the container:
    #expose:
    #- "3306"
    # Where the data will be persisted:
    #volumes:
    #- my-db:/var/lib/mysql

#Name the volume:
#volumes:
# my-db: