version: "3"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
    - "./{{ cookiecutter.project_slug }}/:/code/"
    ports:
    - "8888:8888"
    depends_on: 
    - mysql
    tty: true
      #environment:
       # DB_NAME: mysql
        #DB_PORT: 3306
        #DB_USER: root
        #DB_PWD: password
    command: /bin/bash
  
  #ubuntu:
    #image: ubuntu:18.04
    #ports:
    #- "80:80"
    #- "443:443"

  mysql:
    image: mysql
    environment:
      MSQL_ROOT_PASSWORD: "password"
      MSQL_USER: "user"
      MSQL_DATABASE: "{{ cookiecutter.project_slug }}_db"
    # To persist data on the container:
    ports: 
    - "3306:3306"  
    # Where the data will be persisted:
    volumes:
    - "./{{ cookiecutter.project_slug }}/data/:/var/lib/mysql/"

 